sudo: required
language: groovy
jdk:
- openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
branches:
  only:
  - master
  - /[\d]+\.\d+/
git:
  depth: false
env:
  global:
  - DOCKER_REPO=latera%2Fcamunda
  - REPO=${TRAVIS_REPO_SLUG}
  - COMMIT=${TRAVIS_COMMIT::8}
script:
  - ./test.sh
  - ./docs.sh
#  - git checkout docs/test-reports
#  - if git status docs | grep modified; then echo 'Documentation is outdated!' && exit 1; fi
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; fi
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "target/*.jar"
    skip_cleanup: true
    overwrite: true
    on:
      repo: latera/camunda-ext
      all_branches: true
      condition: $TRAVIS_TAG =~ ^([0-9]+.[0-9]+)$ || $TRAVIS_BRANCH =~ ^([0-9]+.[0-9]+)$
