sudo: required
language: groovy
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - target/dependencies
    - docker_images
branches:
  only:
  - master
  - /[\d]+\.\d+/
env:
  global:
    - DOCKERHUB_REPO=latera/camunda
git:
  depth: false
before_install:
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  - docker load -i docker_images/images.tar || true
before_cache:
  - docker system prune -f
  - docker save -o docker_images/images.tar $(docker images -a -q)
script:
  - ./test.sh
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./docs.sh; fi
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - "target/*.jar"
      - "target/*.war"
      - "seed/target/*.war"
      - "demo_processes/**/target/*.war"
    skip_cleanup: true
    overwrite: true
    on:
      repo: latera/camunda-ext
      all_branches: true
      condition: $TRAVIS_TAG =~ ^([0-9]+.[0-9]+)(.[0-9]+)?$
  - provider: script
    script: docker tag $DOCKERHUB_REPO:$TRAVIS_JOB_ID $DOCKERHUB_REPO:$TRAVIS_TAG && docker push $DOCKERHUB_REPO:$TRAVIS_TAG
    skip_cleanup: true
    on:
      repo: latera/camunda-ext
      all_branches: true
      condition: $TRAVIS_TAG =~ ^([0-9]+.[0-9]+)(.[0-9]+)?$
  - provider: script
    script: docker tag $DOCKERHUB_REPO:$TRAVIS_JOB_ID $DOCKERHUB_REPO:latest && docker push $DOCKERHUB_REPO:latest
    skip_cleanup: true
    on:
      repo: latera/camunda-ext
      branch: master
